In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/FAF5.7.1_2018-2024_half.csv')

In [2]:
# 1. 연도 목록 추출
years = [2018, 2019, 2020, 2021, 2022, 2023, 2024]

# 2. 고정 컬럼
id_cols = [
    "dms_orig", "dms_dest",
    "fr_orig", "fr_dest",
    "dms_mode", "fr_inmode", "fr_outmode",
    "sctg2",
    "trade_type",
    "dist_band"
]

# 3. long 포맷용 데이터 생성
dfs = []

for y in years:
    temp = df[id_cols].copy()
    temp["year"] = y
    temp["tons"] = df[f"tons_{y}"]
    temp["value"] = df.get(f"value_{y}")
    temp["current_value"] = df.get(f"current_value_{y}")
    temp["tmiles"] = df.get(f"tmiles_{y}")
    dfs.append(temp)

df_long = pd.concat(dfs, ignore_index=True)

### 음수 데이터 확인

In [3]:
# 전체 컬럼 중 음수 데이터 확인
cols = [col for col in df_long.columns] 

print("--- 컬럼별 음수 데이터 개수 ---")
print((df_long[cols] < 0).sum())

--- 컬럼별 음수 데이터 개수 ---
dms_orig         0
dms_dest         0
fr_orig          0
fr_dest          0
dms_mode         0
fr_inmode        0
fr_outmode       0
sctg2            0
trade_type       0
dist_band        0
year             0
tons             0
value            0
current_value    0
tmiles           0
dtype: int64

In [23]:
tons_0 = df_long.loc[(df_long['tons'] == 0),['tons','value','current_value','tmiles']].apply(sum)
print(tons_0)

tons_0_df = df_long.loc[(df_long['tons'] == 0)]
tons_0_df.head()

tons              0.000000
value            30.759039
current_value    35.249362
tmiles            0.001731
dtype: float64

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
518714,20,20,801.0,NaN,5,5.0,NaN,1,2,6,2018,0.0,0.0,0.0,0.0
518721,61,121,801.0,NaN,5,5.0,NaN,1,2,8,2018,0.0,0.0,0.0,0.0
518722,61,122,801.0,NaN,5,5.0,NaN,1,2,8,2018,0.0,0.0,0.0,0.0
518723,61,123,801.0,NaN,5,5.0,NaN,1,2,8,2018,0.0,0.0,0.0,0.0
518724,61,124,801.0,NaN,5,5.0,NaN,1,2,8,2018,0.0,0.0,0.0,0.0

In [26]:
tons_0_df['dist_band'].value_counts()

dist_band
8    1115830
6     985003
3     791891
4     736781
5     707630
7     637250
2     427987
1     178208
Name: count, dtype: int64

In [ ]:
# 항공 / 트럭 / 기차 / 배 / 메일?소포?
tons_0_df['dms_mode'].value_counts()

dms_mode
4    2260427
1    1205077
2    1029447
5     863147
3     123996
7      93791
6       4382
8        313
Name: count, dtype: int64

In [30]:
print(tons_0_df['fr_orig'].notna().sum() + tons_0_df['fr_dest'].notna().sum())

print(len(tons_0_df))

5580580
5580580

In [31]:
value_0 = df_long.loc[(df_long['value'] == 0),['tons','value','current_value','tmiles']].apply(sum)
print(value_0)

value_0_df = df_long.loc[(df_long['value'] == 0)]
value_0_df.head()

tons             287922.006766
value                 0.000000
current_value         0.000000
tmiles            45904.267380
dtype: float64

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
489039,19,61,NaN,NaN,1,NaN,NaN,41,1,8,2018,0.000571,0.0,0.0,0.001178
489041,19,182,NaN,NaN,1,NaN,NaN,41,1,4,2018,0.441184,0.0,0.0,0.234156
489058,19,472,NaN,NaN,1,NaN,NaN,41,1,2,2018,0.678083,0.0,0.0,0.143038
489062,20,20,NaN,NaN,3,NaN,NaN,41,1,4,2018,6.641458,0.0,0.0,3.353718
489065,20,531,NaN,NaN,3,NaN,NaN,41,1,5,2018,60.498798,0.0,0.0,52.843274

In [32]:
value_0_df['sctg2'].value_counts()

sctg2
35    307357
34    287680
38    256605
37    250245
33    243587
24    232110
36    220545
30    219476
40    218528
23    198990
31    193607
39    190533
20    188072
32    185581
7     160880
21    152058
26    144723
3     143984
41    142561
29    141063
28    134723
27    124441
4     119584
43    114705
13    101885
5     100039
6      97489
22     87878
8      85584
2      64176
18     62744
19     61814
1      55605
25     50822
14     44303
17     41248
11     36142
9      33143
12     30983
10     23200
15     22364
16      3955
Name: count, dtype: int64

In [40]:
print( (value_0_df['fr_orig'].notna().sum() + value_0_df['fr_dest'].notna().sum()) / len(value_0_df) )

0.9997991035714363

In [41]:
current_value_0 = df_long.loc[(df_long['current_value'] == 0),['tons','value','current_value','tmiles']].apply(sum)
print(current_value_0)

current_value_0_df = df_long.loc[(df_long['current_value'] == 0)]
current_value_0_df.head()

tons             287922.006766
value                 0.000000
current_value         0.000000
tmiles            45904.267380
dtype: float64

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
489039,19,61,NaN,NaN,1,NaN,NaN,41,1,8,2018,0.000571,0.0,0.0,0.001178
489041,19,182,NaN,NaN,1,NaN,NaN,41,1,4,2018,0.441184,0.0,0.0,0.234156
489058,19,472,NaN,NaN,1,NaN,NaN,41,1,2,2018,0.678083,0.0,0.0,0.143038
489062,20,20,NaN,NaN,3,NaN,NaN,41,1,4,2018,6.641458,0.0,0.0,3.353718
489065,20,531,NaN,NaN,3,NaN,NaN,41,1,5,2018,60.498798,0.0,0.0,52.843274

In [42]:
print( (current_value_0_df['fr_orig'].notna().sum() + current_value_0_df['fr_dest'].notna().sum()) / len(current_value_0_df) )

0.9997991035714363

In [43]:
tmiles_0 = df_long.loc[(df_long['tmiles'] == 0),['tons','value','current_value','tmiles']].apply(sum)
print(tmiles_0)

tmiles_0_df = df_long.loc[(df_long['tmiles'] == 0)]
tmiles_0_df.head()

tons             893439.439205
value            300213.334175
current_value    403754.626989
tmiles                0.000000
dtype: float64

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
413847,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2018,0.00006,0.028537,0.028919,0.0
435727,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2018,0.00005,0.008678,0.008941,0.0
518714,20,20,801.0,NaN,5,5.0,NaN,1,2,6,2018,0.00000,0.000000,0.000000,0.0
518721,61,121,801.0,NaN,5,5.0,NaN,1,2,8,2018,0.00000,0.000000,0.000000,0.0
518722,61,122,801.0,NaN,5,5.0,NaN,1,2,8,2018,0.00000,0.000000,0.000000,0.0

In [44]:
print( (tmiles_0_df['fr_orig'].notna().sum() + tmiles_0_df['fr_dest'].notna().sum()) / len(tmiles_0_df) )

0.9999974980963193

In [46]:
tmiles_0_df[tmiles_0_df[['fr_orig','fr_dest']].isna().all(axis = 1)]

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
413847,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2018,0.000060,0.028537,0.028919,0.0
435727,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2018,0.000050,0.008678,0.008941,0.0
2889127,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2019,0.000059,0.028178,0.029110,0.0
2911007,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2019,0.000047,0.008097,0.008626,0.0
5364407,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2020,0.000057,0.027091,0.028389,0.0
5386287,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2020,0.000042,0.007306,0.007948,0.0
7839687,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2021,0.000059,0.027945,0.029705,0.0
7861567,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2021,0.000040,0.006904,0.008043,0.0
10314967,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2022,0.000057,0.027091,0.030521,0.0
10336847,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2022,0.000042,0.007184,0.009407,0.0
12790247,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2023,0.000055,0.026343,0.031163,0.0
12812127,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2023,0.000040,0.006821,0.009348,0.0
15265527,111,111,NaN,NaN,5,NaN,NaN,38,1,1,2024,0.000054,0.025730,0.031384,0.0
15287407,111,111,NaN,NaN,5,NaN,NaN,39,1,1,2024,0.000039,0.006763,0.009418,0.0

In [20]:
df_long.loc[(df_long['value'] == 0),['tons','value','current_value','tmiles']].apply(sum)

tons             287922.006766
value                 0.000000
current_value         0.000000
tmiles            45904.267380
dtype: float64

In [ ]:
outliers_3 = df_long[
    (df_long['tons'] == 0) & (df_long['value'] == 0) & (df_long['tmiles'] == 0)
]

# 모두 0
outliers_3[['tons','value','current_value','tmiles']].apply(sum)

tons             0.0
value            0.0
current_value    0.0
tmiles           0.0
dtype: float64

In [ ]:
outliers_3['sctg2'].value_counts()

sctg2
35    307357
34    287680
38    256605
37    250245
33    243587
24    232110
36    220545
30    219476
40    218528
23    198990
31    193607
39    190533
20    188072
32    185581
7     160880
21    152058
26    144723
3     143984
41    141441
29    141063
28    134723
27    124441
4     119584
43    114705
13    101885
5     100039
6      97489
22     87878
8      85584
2      64176
18     62744
19     61814
1      55605
25     50822
14     44303
17     41248
11     36142
9      33143
12     30983
10     23200
15     22364
16      3955
Name: count, dtype: int64

In [4]:
outliers_1 = df_long[
    (df_long['tons'] == 0) & ((df_long['value'] > 0) | (df_long['tmiles'] > 0))
]

In [7]:
outliers_1

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
535086,212,373,801.0,NaN,4,4.0,NaN,3,2,3,2018,0.0,0.001226,0.001232,0.0
550349,471,369,805.0,NaN,4,4.0,NaN,3,2,5,2018,0.0,0.001473,0.001481,0.0
553918,471,401,806.0,NaN,4,4.0,NaN,3,2,3,2018,0.0,0.001071,0.001076,0.0
556181,212,291,807.0,NaN,4,4.0,NaN,3,2,3,2018,0.0,0.001178,0.001184,0.0
556182,212,292,807.0,NaN,4,4.0,NaN,3,2,3,2018,0.0,0.001813,0.001822,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17326742,481,212,NaN,808.0,4,NaN,4.0,43,3,5,2024,0.0,0.000970,0.001310,0.0
17326771,484,212,NaN,808.0,4,NaN,4.0,43,3,4,2024,0.0,0.004230,0.005708,0.0
17326793,486,212,NaN,808.0,4,NaN,4.0,43,3,5,2024,0.0,0.003556,0.004799,0.0
17326810,488,212,NaN,808.0,4,NaN,4.0,43,3,5,2024,0.0,0.000812,0.001096,0.0
17326821,489,212,NaN,808.0,4,NaN,4.0,43,3,5,2024,0.0,0.002274,0.003069,0.0

In [8]:
# 0.01보다 큰 값
outliers_2 = outliers_1[
    (outliers_1['value'] > 0.01) | (outliers_1['tmiles'] > 0.01)
]

print(f"--- 0.01 초과 이상치 개수 ---")
print(f"검출된 행 수: {len(outliers_2)}건")

outliers_2

--- 0.01 초과 이상치 개수 ---
검출된 행 수: 386건

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
705873,49,62,802.0,NaN,6,6.0,NaN,19,2,4,2018,0.0,0.084954,0.088734,0.0
705874,49,63,802.0,NaN,6,6.0,NaN,19,2,2,2018,0.0,0.108867,0.113710,0.0
705876,49,65,802.0,NaN,6,6.0,NaN,19,2,3,2018,0.0,0.037390,0.039053,0.0
705877,49,69,802.0,NaN,6,6.0,NaN,19,2,3,2018,0.0,0.157432,0.164436,0.0
705908,69,65,802.0,NaN,5,5.0,NaN,19,2,2,2018,0.0,0.032839,0.034300,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17253866,109,212,NaN,801.0,4,NaN,4.0,40,3,4,2024,0.0,0.010133,0.014774,0.0
17255008,219,362,NaN,801.0,4,NaN,4.0,40,3,4,2024,0.0,0.027491,0.040083,0.0
17277112,81,122,NaN,806.0,4,NaN,4.0,40,3,7,2024,0.0,0.014931,0.021770,0.0
17279430,363,122,NaN,806.0,4,NaN,4.0,40,3,6,2024,0.0,0.063466,0.092537,0.0
17279542,369,122,NaN,806.0,4,NaN,4.0,40,3,6,2024,0.0,0.013859,0.020207,0.0

In [9]:
outliers_2["fr_inmode"].value_counts()

fr_inmode
4.0    223
7.0     16
5.0      7
6.0      4
1.0      2
Name: count, dtype: int64

In [10]:
# 어떤 상품(sctg2)이나 경로에서 많이 발생하는지 요약
if not outliers_2.empty:
    print("\n[이상치 발생 빈도 상위 상품군]")
    print(outliers_2['sctg2'].value_counts())
    
    # 샘플 데이터 확인
    display(outliers_2.head(10))

[이상치 발생 빈도 상위 상품군]
sctg2
40    138
20     95
21     95
35     18
37     11
38      6
19      5
29      5
34      5
39      2
33      2
24      2
41      1
23      1
Name: count, dtype: int64

,dms_orig,dms_dest,fr_orig,fr_dest,dms_mode,fr_inmode,fr_outmode,sctg2,trade_type,dist_band,year,tons,value,current_value,tmiles
705873,49,62,802.0,NaN,6,6.0,NaN,19,2,4,2018,0.0,0.084954,0.088734,0.0
705874,49,63,802.0,NaN,6,6.0,NaN,19,2,2,2018,0.0,0.108867,0.113710,0.0
705876,49,65,802.0,NaN,6,6.0,NaN,19,2,3,2018,0.0,0.037390,0.039053,0.0
705877,49,69,802.0,NaN,6,6.0,NaN,19,2,3,2018,0.0,0.157432,0.164436,0.0
705908,69,65,802.0,NaN,5,5.0,NaN,19,2,2,2018,0.0,0.032839,0.034300,0.0
721894,123,179,804.0,NaN,4,4.0,NaN,20,2,5,2018,0.0,0.028175,0.030668,0.0
721908,123,371,804.0,NaN,4,4.0,NaN,20,2,3,2018,0.0,0.058187,0.063335,0.0
721909,123,372,804.0,NaN,4,4.0,NaN,20,2,4,2018,0.0,0.042222,0.045958,0.0
721910,123,373,804.0,NaN,4,4.0,NaN,20,2,4,2018,0.0,0.055743,0.060675,0.0
722905,211,421,804.0,NaN,4,4.0,NaN,20,2,3,2018,0.0,0.040985,0.044611,0.0

In [11]:
outliers_2.groupby('trade_type').size().sort_values(ascending=False)
outliers_2.groupby('fr_orig').size().sort_values(ascending=False)
outliers_2.groupby('fr_dest').size().sort_values(ascending=False)

fr_dest
803.0    46
806.0    25
808.0    16
804.0    13
801.0    12
805.0    10
802.0     6
807.0     6
dtype: int64

In [12]:
outliers_2['dms_mode'].value_counts()

dms_mode
4    324
1     35
7     16
5      7
6      4
Name: count, dtype: int64